# ROS2 image
FROM ros:foxy-ros-core-focal

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init && \
  rosdep update --rosdistro $ROS_DISTRO

# setup colcon mixin and metadata
RUN colcon mixin add default \
      https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update && \
    colcon metadata add default \
      https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
    colcon metadata update

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-foxy-ros-base=0.9.2-1* \
    && rm -rf /var/lib/apt/lists/*

#install rosbridge
RUN apt-get update && apt-get install -y ros-foxy-rosbridge-suite
#install turtlesim
RUN apt install ros-foxy-turtlesim -y
#source ros
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc

#install pip
RUN apt-get update && apt-get install -y \
    python3-pip

#setup workdir
WORKDIR /app

COPY ./turtle_engine .
COPY ./turtle_engine_docker_cmd.sh .

RUN pip install -r requirements.txt

RUN chmod +x ./turtle_engine_docker_cmd.sh
CMD sh ./turtle_engine_docker_cmd.sh
